# Generated by Django 5.0.6 on 2024-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='title',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
