# Generated by Django 5.0.6 on 2024-06-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookings_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='booking_id',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
